export const AchievementsRows = [
    {
        id: 1,
        year: 2024,
        venue: 'Sharjah International Show Jumping Championship & Nations Cup / Dubai, UAE',
        horse: 'Dourados 2',
        individualRank: 3,
        teamRank: '',
    },
    {
        id: 2,
        year: 2023,
        venue: 'Continental/Regional Championships Milano, San Siro',
        horse: 'Dourados 2',
        individualRank: 53,
        teamRank: 14,
    },
    {
        id: 3,
        year: 2018,
        venue: 'FEI World Equestrian GamesTM Tryon NC',
        horse: 'Sig Winter Soldier',
        individualRank: 100,
        teamRank: 21,
    },
    {
        id: 4,
        year: 2018,
        venue: 'Continental/Regional Games Barcelona',
        horse: 'Sig Winter Soldier',
        individualRank: 1, // Assuming '1 (FEI Gold Medal)' means a special achievement
        teamRank: '', // 'FEI Gold Medal' doesn't directly map to a numeric rank, so marking as 'N/A'
    },
    {
        id: 5,
        year: 2018,
        venue: 'Continental/Regional Games Barcelona',
        horse: 'Sig Winter Soldier',
        individualRank: 7,
        teamRank: '', // Assuming this was intended as individual rank with no team rank provided
    },
    {
        id: 6,
        year: 2014,
        venue: "Young Horses World Championship Le Lion d'Angers",
        horse: 'Z',
        individualRank: 7,
        teamRank: '',
    },
    {
        id: 7,
        year: 2011,
        venue: "Young Horses World Championship Le Lion d'Angers",
        horse: 'Fernhill Pimms',
        individualRank: 36,
        teamRank: '',
    },
    {
        id: 8,
        year: 2011,
        venue: "Young Horses World Championship Le Lion d'Angers",
        horse: 'Castleview Red',
        individualRank: 'EL', // Assuming 'EL' is a code for elimination or similar
        teamRank: '',
    },
    {
        id: 9,
        year: 2010,
        venue: 'FEI World Equestrian GamesTM Lexington, KY (Horse Park)',
        horse: 'Fernhill Gloster Rebel',
        individualRank: 'WD', // Assuming 'WD' signifies withdrawal
        teamRank: '',
    },
    {
        id: 10,
        year: 2009,
        venue: "Young Horses World Championship Le Lion d'Angers",
        horse: 'Fernhill M2s',
        individualRank: 'EL',
        teamRank: '',
    },
    {
        id: 11,
        year: 2009,
        venue: 'Continental/Regional Championships Fontainebleau',
        horse: 'Brave Heart',
        individualRank: 28,
        teamRank: '',
    },
    {
        id: 12,
        year: 2008,
        venue: "Young Horses World Championship Le Lion d'Angers",
        horse: 'Fernhill Urco',
        individualRank: 14,
        teamRank: '',
    },
    {
        id: 13,
        year: 2008,
        venue: "Young Horses World Championship Le Lion d'Angers",
        horse: 'Fernhill Gloster Rebel',
        individualRank: 22,
        teamRank: '',
    },
    {
        id: 14,
        year: 2007,
        venue: "Young Horses World Championship Le Lion d'Angers",
        horse: 'Upper',
        individualRank: 'EL',
        teamRank: '',
    },
    {
        id: 15,
        year: 2006,
        venue: "Young Horses World Championship Le Lion d'Angers",
        horse: 'Tarzan Da Graciosa',
        individualRank: 22,
        teamRank: '',
    },
    {
        id: 16,
        year: 2005,
        venue: 'Continental/Regional Championships Blenheim',
        horse: 'Zebedee',
        individualRank: 'RET', // Assuming 'RET' signifies retirement
        teamRank: 10,
    },
    {
        id: 17,
        year: 2004,
        venue: "Continental/Regional Championships Barroca d'Alva",
        horse: 'No Limit',
        individualRank: 28,
        teamRank: 8,
    },
    {
        id: 18,
        year: 2003,
        venue: 'Youth Continental/Regional Championships Pardubice',
        horse: 'Joia Da Valada',
        individualRank: 22,
        teamRank: 11,
    },
    {
        id: 19,
        year: 2002,
        venue: 'Youth Continental/Regional Championships Waregem',
        horse: 'Joia Da Valada',
        individualRank: 39,
        teamRank: 11,
    },
];
